# dc -f separate.yml build --no-cache 
# dc -f separate.yml up --build --remove-orphans
# dc -f separate.yml up --build -d

# https://docs.docker.com/compose/compose-file/

version: "3.9"
services:
  backend:
    container_name: backend
    image: node:17
    build: ./backend
    restart: always
    ports:
     - "9001:9001"
    depends_on:
      db:
        condition: service_healthy
  frontend:
    container_name: frontend
    image: nginx:latest
    build: ./frontend
    ports:
      - "80:80"
  db:
    container_name: db
    image: mysql:5.7
    build: ./db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql